#!/bin/bash

SESSIONNAME="workspace"
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]
    then

        # new session with name $SESSIONNAME and window 0 named "base"
        tmux new-session -s $SESSIONNAME -n "htop" -d "htop"

        # new window for gen stuff
        tmux new-window -t $SESSIONNAME -n "Syslog"
        tmux send-keys 'cd' 'C-m'
        tmux send-keys 'grc tailf /var/log/syslog' 'C-m'

        # new window for gen stuff
        tmux new-window -t $SESSIONNAME -n "Gen"
        tmux send-keys 'cd' 'C-m'

fi

tmux attach -t $SESSIONNAME

